name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create firebaseConfig.js
        run: |
          cat <<EOF > sistema_de_monitoramento/static/js/firebaseConfig.js
          import { initializeApp } from "https://www.gstatic.com/firebasejs/9.22.2/firebase-app.js";
          import { getFirestore } from "https://www.gstatic.com/firebasejs/9.22.2/firebase-firestore.js";
          import { getAuth } from "https://www.gstatic.com/firebasejs/9.22.2/firebase-auth.js";
          
          const firebaseConfig = ${{ secrets.FIREBASE_CONFIG }};
          
          const app = initializeApp(firebaseConfig);
          const db = getFirestore(app);
          const auth = getAuth(app);
          
          export { db, auth, app };
          EOF

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DETECCAO_DE_EPI }}'
          channelId: live
          projectId: testerasp1-fd9ce