name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create firebaseConfig.js
        run: |
          mkdir -p sistema_de_monitoramento/static/js
          echo "import { initializeApp } from 'https://www.gstatic.com/firebasejs/9.22.2/firebase-app.js';
          import { getFirestore } from 'https://www.gstatic.com/firebasejs/9.22.2/firebase-firestore.js';
          import { getAuth } from 'https://www.gstatic.com/firebasejs/9.22.2/firebase-auth.js';
          
          const firebaseConfig = {
            apiKey: '${{ secrets.FIREBASE_API_KEY }}',
            authDomain: '${{ secrets.FIREBASE_AUTH_DOMAIN }}',
            projectId: '${{ secrets.FIREBASE_PROJECT_ID }}',
            storageBucket: '${{ secrets.FIREBASE_STORAGE_BUCKET }}',
            messagingSenderId: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}',
            appId: '${{ secrets.FIREBASE_APP_ID }}',
            databaseURL: '${{ secrets.FIREBASE_DATABASE_URL }}'
          };
          
          const app = initializeApp(firebaseConfig);
          const db = getFirestore(app);
          const auth = getAuth(app);
          
          export { db, auth, app };" > sistema_de_monitoramento/static/js/firebaseConfig.js

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_JUPITER_SUPERVISION }}'
          channelId: live
          projectId: jupiter-supervision